### ISSUE TITLE
Add option for the color of edges

### ISSUE THREAD

**Issue by axkr** [jsxgraph/json2D_JSXGraph#6]
Please add an option for the color and opacity of edges for "disk", "rectangle" etc objects. 

I would suggest something like:
```json
{
    "option": "edgeForm",
    "value": [0.0, 0.0, 0.0]
    "opacity": 0.2
 }
```

See:
- https://jsfiddle.net/axelclk/3wke1s7h/5/

**Comment by Haspeldor** [comment]
Thank you for the suggestion, something like this could be easily implemented!

However I wouldn't add a another attribute to the option besides "value", because of how an option is currently processed.
I would suggest either using a json object as value or splitting up the attribute in two separate ones.
So either:
'''
{
    "option": "edgeForm",
    "value": {"color": [0.0, 0.0, 0.0], "opacity": 0.2}
 }
'''
or:
'''
{
    "option": "edgeColor",
    "value": [0.0, 0.0, 0.0]
 },
{
    "option": "edgeOpacity",
    "value": "opacity": 0.2
 }
'''
What do you think about that?

**Comment by Haspeldor** [comment]
Thank you for the suggestion, something like this could be easily implemented!
However I wouldn't add a another attribute to the option besides "value", because of how an option is currently processed.
I would suggest either using a json object as value or splitting up the attribute in two seperate ones.
So either:
`
{
    "option": "edgeForm",
    "value": {"color": [0.0, 0.0, 0.0], "opacity": 0.2}
 }
`
or:
`
{
    "option": "edgeColor",
    "value": [0.0, 0.0, 0.0]
 },
{
    "option": "edgeOpacity",
    "value": "opacity": 0.2
 }
`
What do you think about that?

**Comment by Haspeldor** [comment]
Thank you for the suggestion, something like this could be easily implemented!
However I wouldn't add a another attribute to the option besides "value", because of how an option is currently processed.
I would suggest either using a json object as value or splitting up the attribute in two seperate ones.
So either:
`{ "option": "edgeForm", "value": {"color": [0.0, 0.0, 0.0], "opacity": 0.2} }`
or:
`{ "option": "edgeColor", "value": [0.0, 0.0, 0.0] }, { "option": "edgeOpacity", "value": 0.2 }`
What do you think about that?
